# Generated by Django 4.1.3 on 2022-12-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EshartApp', '0002_admin_city_terminal_travel_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=30)),
                ('site', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='admin',
        ),
    ]
