# Generated by Django 4.1.3 on 2022-12-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EshartApp', '0003_admin1_delete_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
