# Generated by Django 4.1.3 on 2022-12-21 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EshartApp', '0004_travel_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supporter',
            old_name='phoneNumber',
            new_name='phoneNumber2',
        ),
        migrations.RemoveField(
            model_name='supporter',
            name='email',
        ),
        migrations.RemoveField(
            model_name='supporter',
            name='name',
        ),
        migrations.AddField(
            model_name='supporter',
            name='phoneNumber1',
            field=models.CharField(default=0, max_length=11),
        ),
        migrations.AddField(
            model_name='supporter',
            name='telegram',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='supporter',
            name='whatsapp',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger', to='EshartApp.passenger'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='travelTime',
            field=models.TimeField(null=True),
        ),
    ]
