# Generated by Django 4.1.3 on 2022-12-22 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EshartApp', '0007_alter_admin1_site'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin1',
            old_name='password',
            new_name='passAdmin',
        ),
        migrations.RenameField(
            model_name='admin1',
            old_name='username',
            new_name='userAdmin',
        ),
    ]
