# Generated by Django 4.1.3 on 2022-12-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EshartApp', '0008_rename_password_admin1_passadmin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin1',
            name='passAdmin',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='admin1',
            name='userAdmin',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
